apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: seed-service
    spec:
      containers:
        - name: seed-service
          image: scrscontainerregistry.azurecr.io/seed-archetype:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: seed-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: seed-service
